<?php

$GLOBALS['PLUGINS'] =  array(
	'warranty' =>  array(
		'plugin_creator_URI' => 'http://openkeyos.fortelogics.ro', 
		'plugin_creator' => 'Victor Cristinari', 
		'plugin_version' => '1.0', 
		'plugin_desc' => 'Warranties plugin', 
		'plugin_name' => 'Warranty', 
		'plugin_dir' => __DIR__ . '/Warranty', 
	), 
	'customer' =>  array(
		'plugin_creator_URI' => 'http://openkeyos.fortelogics.ro', 
		'plugin_creator' => 'Victor Cristinari', 
		'plugin_version' => '1.0', 
		'plugin_desc' => 'Customers plugin', 
		'plugin_name' => 'Customer', 
		'plugin_dir' => __DIR__ . '/Customer', 
	), 
	'customer_krifs' =>  array(
		'plugin_creator_URI' => 'http://openkeyos.fortelogics.ro', 
		'plugin_creator' => 'Victor Cristinari', 
		'plugin_version' => '1.0', 
		'plugin_desc' => 'Customer KRIFS plugin', 
		'plugin_name' => 'CustomerKRIFS', 
		'plugin_dir' => __DIR__ . '/CustomerKRIFS', 
	), 
	'computer' =>  array(
		'plugin_creator_URI' => 'http://openkeyos.fortelogics.ro', 
		'plugin_creator' => 'Victor Cristinari', 
		'plugin_version' => '1.0', 
		'plugin_desc' => 'Computer', 
		'plugin_name' => 'Computer', 
		'plugin_dir' => __DIR__ . '/Computer', 
	), 
	'snmp' =>  array(
		'plugin_creator_URI' => 'http://openkeyos.fortelogics.ro', 
		'plugin_creator' => 'Victor Cristinari', 
		'plugin_version' => '1.0', 
		'plugin_desc' => 'KeyOS Snmp module', 
		'plugin_name' => 'SNMP', 
		'plugin_dir' => __DIR__ . '/SNMP', 
	), 
	'erp' =>  array(
		'plugin_creator_URI' => 'http://openkeyos.fortelogics.ro', 
		'plugin_creator' => 'Victor Cristinari', 
		'plugin_version' => '1.0', 
		'plugin_desc' => 'ERP - Keyos ERP connection module', 
		'plugin_name' => 'ERP', 
		'plugin_dir' => __DIR__ . '/ERP', 
	), 
	'test_xx' =>  array(
		'plugin_creator_URI' => '', 
		'plugin_creator' => '', 
		'plugin_version' => '1.0', 
		'plugin_desc' => '', 
		'plugin_name' => 'TestXX', 
		'plugin_dir' => __DIR__ . '/TestXX', 
	), 
	'asterisk' =>  array(
		'plugin_creator_URI' => 'http://openkeyos.fortelogics.ro', 
		'plugin_creator' => 'Victor Cristinari', 
		'plugin_version' => '1.0', 
		'plugin_desc' => 'Asterisk plugin', 
		'plugin_name' => 'Asterisk', 
		'plugin_dir' => __DIR__ . '/Asterisk', 
	), 
	'customer_kerm' =>  array(
		'plugin_creator_URI' => 'http://openkeyos.fortelogics.ro', 
		'plugin_creator' => 'Victor Cristinari', 
		'plugin_version' => '1.0', 
		'plugin_desc' => 'Customer KERM plugin', 
		'plugin_name' => 'CustomerKERM', 
		'plugin_dir' => __DIR__ . '/CustomerKERM', 
	), 
	'kalm' =>  array(
		'plugin_creator_URI' => 'http://openkeyos.fortelogics.ro', 
		'plugin_creator' => 'Victor Cristinari', 
		'plugin_version' => '1.0', 
		'plugin_desc' => 'KALM - Keyos Advanced Licence Manager', 
		'plugin_name' => 'KALM', 
		'plugin_dir' => __DIR__ . '/KALM', 
	), 
	'customer_reports' =>  array(
		'plugin_creator_URI' => 'http://openkeyos.fortelogics.ro', 
		'plugin_creator' => 'Victor Cristinari', 
		'plugin_version' => '1.0', 
		'plugin_desc' => 'Customer Reports plugin', 
		'plugin_name' => 'CustomerReports', 
		'plugin_dir' => __DIR__ . '/CustomerReports', 
	), 
	'kawacs' =>  array(
		'plugin_creator_URI' => 'http://openkeyos.fortelogics.ro', 
		'plugin_creator' => 'Victor Cristinari', 
		'plugin_version' => '1.0', 
		'plugin_desc' => 'KAWACS', 
		'plugin_name' => 'KAWACS', 
		'plugin_dir' => __DIR__ . '/KAWACS', 
	),
    'kams' =>  array(
        'plugin_creator_URI' => 'http://openkeyos.fortelogics.ro',
        'plugin_creator' => 'Victor Cristinari',
        'plugin_version' => '1.0',
        'plugin_desc' => 'KAMS',
        'plugin_name' => 'KAMS',
        'plugin_dir' => __DIR__ . '/KAMS',
    ),
    'customer_kawacs' =>  array(
		'plugin_creator_URI' => 'http://openkeyos.fortelogics.ro', 
		'plugin_creator' => 'Victor Cristinari', 
		'plugin_version' => '1.0', 
		'plugin_desc' => 'Customer KAWACS plugin', 
		'plugin_name' => 'CustomerKAWACS', 
		'plugin_dir' => __DIR__ . '/CustomerKAWACS', 
	), 
	'kerm' =>  array(
		'plugin_creator_URI' => 'http://openkeyos.fortelogics.ro', 
		'plugin_creator' => 'Victor Cristinari', 
		'plugin_version' => '1.0', 
		'plugin_desc' => 'KERM - Keyos Enterprise Resource Manager', 
		'plugin_name' => 'KERM', 
		'plugin_dir' => __DIR__ . '/KERM', 
	), 
	'krifs' =>  array(
		'plugin_creator_URI' => 'http://openkeyos.fortelogics.ro', 
		'plugin_creator' => 'Victor Cristinari', 
		'plugin_version' => '1.0', 
		'plugin_desc' => 'KRIFS - Tickting system and Intervention Reports', 
		'plugin_name' => 'KRIFS', 
		'plugin_dir' => __DIR__ . '/KRIFS', 
	), 
	'knowledgebase' =>  array(
		'plugin_creator_URI' => 'http://openkeyos.fortelogics.ro', 
		'plugin_creator' => 'Victor Cristinari', 
		'plugin_version' => '1.0', 
		'plugin_desc' => 'KeyOS KnowledgeBase module', 
		'plugin_name' => 'KnowledgeBase', 
		'plugin_dir' => __DIR__ . '/KnowledgeBase', 
	), 
	'test' =>  array(
		'plugin_creator_URI' => 'http://openkeyos.fortelogics.ro', 
		'plugin_creator' => 'Victor Cristinari', 
		'plugin_version' => '1.0', 
		'plugin_desc' => 'Test plugin', 
		'plugin_name' => 'TestPlugin', 
		'plugin_dir' => __DIR__ . '/TestPlugin', 
	), 
	'klara' =>  array(
		'plugin_creator_URI' => 'http://openkeyos.fortelogics.ro', 
		'plugin_creator' => 'Victor Cristinari', 
		'plugin_version' => '1.0', 
		'plugin_desc' => 'KLARA - access information plugin', 
		'plugin_name' => 'KLARA', 
		'plugin_dir' => __DIR__ . '/KLARA', 
	), 
	'supplier' =>  array(
		'plugin_creator_URI' => 'http://openkeyos.fortelogics.ro', 
		'plugin_creator' => 'Victor Cristinari', 
		'plugin_version' => '1.0', 
		'plugin_desc' => 'Supplier - Keyos suppliers module', 
		'plugin_name' => 'Supplier', 
		'plugin_dir' => __DIR__ . '/Supplier', 
	), 
	'krifs_metrics' =>  array(
		'plugin_creator_URI' => 'http://openkeyos.fortelogics.ro', 
		'plugin_creator' => 'Victor Cristinari', 
		'plugin_version' => '1.0', 
		'plugin_desc' => 'Krifs Metrics', 
		'plugin_name' => 'KrifsMetrics', 
		'plugin_dir' => __DIR__ . '/KrifsMetrics', 
	), 
);